// ─────────────────────────────────────────────────────────────────────────
// EPISODE 6 — paste this object into the EPISODES array in
// scripts/generate-maths-podcast-audio.mjs, after the episode 5 block
// (i.e. immediately before the closing  ];  on the last line).
// Then run:   node --env-file=.env.local scripts/generate-maths-podcast-audio.mjs 6
// ─────────────────────────────────────────────────────────────────────────
{
  num: 6,
  file: 'Episode 6 - Finite Geometric Series',
  segs: [
    { s: 'AMELIA',  t: `Episode six. Finite geometric series.` },
    { s: 'MICHAEL', t: `Last time we added up a sequence that grows by adding. Today we add up one that grows by multiplying.` },
    { s: 'NALEDI',  t: `And you told me I cannot pair those from the outside in.` },
    { s: 'MICHAEL', t: `You cannot. So we need a different trick. And it is a beautiful one.` },
    { s: 'NALEDI',  t: `First, my homework.` },
    { s: 'MICHAEL', t: `Your series was five, plus eight, plus eleven, up to forty seven. Fifteen terms.` },
    { s: 'NALEDI',  t: `The first term is five. The last term is forty seven. And there are fifteen terms.` },
    { s: 'MICHAEL', t: `So which version did you use?` },
    { s: 'NALEDI',  t: `The first plus last one. Fifteen over two, times, five plus forty seven.` },
    { s: 'NALEDI',  t: `The bracket is fifty two. I halved the fifty two instead of the fifteen. That gave twenty six. Then fifteen times twenty six.` },
    { s: 'NALEDI',  t: `Three hundred and ninety.` },
    { s: 'MICHAEL', t: `Three hundred and ninety. And halving the fifty two first was smart. You avoided the decimal completely.` },
    { s: 'MICHAEL', t: `Now watch what happens if you take that same formula into today's topic. Here is a small geometric series. Two, plus four, plus eight.` },
    { s: 'NALEDI',  t: `I can just add those. Fourteen.` },
    { s: 'MICHAEL', t: `You can. Now do it with last week's formula, and see what it gives you.` },
    { s: 'NALEDI',  t: `Three over two, times, two plus eight. That is one comma five, times ten. Fifteen.` },
    { s: 'MICHAEL', t: `Fifteen. But the real answer is fourteen. So the arithmetic formula is wrong here. Why?` },
    { s: 'NALEDI',  t: `Because the pairs are not equal any more. Two and eight make ten, but the middle number is four, not five.` },
    { s: 'MICHAEL', t: `Exactly. Pairing only works when the steps are equal. When the numbers multiply, the pairs go out of balance. So we need something new.` },
    { s: 'MICHAEL', t: `Here is the trick. Take the series, multiply the whole thing by the common ratio, and then subtract.` },
    { s: 'NALEDI',  t: `Subtract it from itself?` },
    { s: 'MICHAEL', t: `Watch. Take two, plus four, plus eight, plus sixteen. Call the total S.` },
    { s: 'MICHAEL', t: `Now multiply every term by two, because two is the ratio.` },
    { s: 'NALEDI',  t: `Four, plus eight, plus sixteen, plus thirty two.` },
    { s: 'MICHAEL', t: `Now subtract the first line from the second.` },
    { s: 'NALEDI',  t: `The four cancels. The eight cancels. The sixteen cancels. Only thirty two and two are left.` },
    { s: 'MICHAEL', t: `So two S, minus S, is thirty two minus two.` },
    { s: 'NALEDI',  t: `So S is thirty.` },
    { s: 'MICHAEL', t: `Check it by adding. Two, four, eight, sixteen.` },
    { s: 'NALEDI',  t: `Thirty. It works.` },
    { s: 'MICHAEL', t: `Now do exactly that with letters. First term a. Common ratio r. And n terms.` },
    { s: 'MICHAEL', t: `Multiply the whole line by r.` },
    { s: 'MICHAEL', t: `Subtract. Everything in the middle cancels again. You are left with a r to the n, minus a.` },
    { s: 'MICHAEL', t: `Take S out on the left, and take a out on the right.` },
    { s: 'NALEDI',  t: `So S is a, times r to the n minus one, all over r minus one.` },
    { s: 'MICHAEL', t: `That is on your formula sheet. And there is a second version, for when the ratio is a fraction, so the bottom stays positive.` },
    { s: 'MICHAEL', t: `Same formula, top and bottom both turned around. Use whichever one keeps you out of negatives.` },
    { s: 'MICHAEL', t: `Now the real one. Same paper, and the same sequence we used in episode two.` },
    { s: 'MICHAEL', t: `Sixteen, four, one, and it carries on. Calculate the sum of the first ten terms.` },
    { s: 'NALEDI',  t: `The first term is sixteen.` },
    { s: 'MICHAEL', t: `And the common ratio? Careful here.` },
    { s: 'NALEDI',  t: `You divide, you do not subtract. Four divided by sixteen. That is a quarter.` },
    { s: 'MICHAEL', t: `Check it once more.` },
    { s: 'NALEDI',  t: `One divided by four is also a quarter. Same answer. So it really is geometric.` },
    { s: 'MICHAEL', t: `The ratio is less than one, so use the version with one minus r on the bottom.` },
    { s: 'NALEDI',  t: `Sixteen, times, one minus a quarter to the power of ten, all over, one minus a quarter.` },
    { s: 'MICHAEL', t: `Do the bottom first.` },
    { s: 'NALEDI',  t: `One minus a quarter is three quarters.` },
    { s: 'MICHAEL', t: `And sixteen divided by three quarters?` },
    { s: 'NALEDI',  t: `Sixteen times four over three. That is sixty four over three. Twenty one comma three three three, and it carries on.` },
    { s: 'MICHAEL', t: `Now the top. A quarter, to the power of ten.` },
    { s: 'NALEDI',  t: `That is about one over a million. Almost nothing.` },
    { s: 'NALEDI',  t: `So the top bracket is almost exactly one.` },
    { s: 'MICHAEL', t: `Which means the answer is almost exactly sixty four over three.` },
    { s: 'NALEDI',  t: `Twenty one comma three three.` },
    { s: 'MICHAEL', t: `Two marks. And notice something. Ten terms, and the total has barely moved off twenty one comma three three. Hold that thought.` },
    { s: 'MICHAEL', t: `Four things.` },
    { s: 'MICHAEL', t: `Number one. You find r by dividing, never by subtracting. Later term, divided by earlier term.` },
    { s: 'MICHAEL', t: `Number two. n counts terms. Ten terms means n is ten. It is never the value of a term.` },
    { s: 'MICHAEL', t: `Number three. Do not round in the middle. Keep the fraction until the end, and round only your final answer.` },
    { s: 'MICHAEL', t: `Number four. If the ratio is a fraction, use the one minus version. Both are on the formula sheet, and both give the same answer, but one keeps you out of negatives.` },
    { s: 'MICHAEL', t: `Three things to remember.` },
    { s: 'MICHAEL', t: `One. Arithmetic adds the same amount. Geometric multiplies by the same amount. The series formula follows the sequence.` },
    { s: 'MICHAEL', t: `Two. The trick is to multiply by r and subtract. Everything in the middle cancels.` },
    { s: 'MICHAEL', t: `Three. The sum is a, times r to the n minus one, over r minus one. Or one minus r to the n, over one minus r, when the ratio is a fraction.` },
    { s: 'MICHAEL', t: `Here is your question. The same series. Sixteen, plus four, plus one, and so on. This time add up twenty terms instead of ten.` },
    { s: 'MICHAEL', t: `Pause and try it. I will wait.`, pause: 3.0 },
    { s: 'MICHAEL', t: `I will give you the answer next time. And I think the answer will surprise you.` },
    { s: 'NALEDI',  t: `Why would twenty terms surprise me?` },
    { s: 'MICHAEL', t: `Because of how little it changes. That is episode seven. We add up an endless number of terms, and still get a finite answer.` },
  ],
  slides: [
    { n:  1, afterSeg:  0, title: `EPISODE 6 • FINITE GEOMETRIC SERIES`, onScreen: `EPISODE 6 — FINITE GEOMETRIC SERIES` },
    { n:  2, afterSeg:  1, title: `ADD VERSUS MULTIPLY`,                 onScreen: `last time it ADDED · today it MULTIPLIES` },
    { n:  3, afterSeg:  3, title: `NO PAIRING THIS TIME`,                onScreen: `pairing needs equal steps — we need a new trick` },
    { n:  4, afterSeg:  5, title: `LAST TIME • FIND THE SUM`,            onScreen: `5 + 8 + 11 + … + 47 · n = 15` },
    { n:  5, afterSeg:  6, title: `WHAT YOU ALREADY HAVE`,               onScreen: `a = 5 · l = 47 · n = 15` },
    { n:  6, afterSeg:  8, title: `SUBSTITUTE`,                          onScreen: `S₁₅ = 15/2 (5 + 47)` },
    { n:  7, afterSeg:  9, title: `HALVE THE 52 FIRST`,                  onScreen: `5 + 47 = 52 → 52 ÷ 2 = 26 → 15 × 26` },
    { n:  8, afterSeg: 10, title: `ANSWER • 390`,                        onScreen: `S₁₅ = 390 ✓ (boxed)` },
    { n:  9, afterSeg: 12, title: `A SMALL GEOMETRIC SERIES`,            onScreen: `2 + 4 + 8` },
    { n: 10, afterSeg: 13, title: `JUST ADD THEM • 14`,                  onScreen: `2 + 4 = 6 → 6 + 8 = 14` },
    { n: 11, afterSeg: 15, title: `THE OLD FORMULA FAILS`,               onScreen: `red · 3/2 (2 + 8) = 15, but the sum is 14` },
    { n: 12, afterSeg: 17, title: `THE PAIRS ARE NOT EQUAL`,             onScreen: `2 + 8 = 10, so the middle should be 5 — but it is 4` },
    { n: 13, afterSeg: 18, title: `PAIRING NEEDS EQUAL STEPS`,           onScreen: `arithmetic pairs · geometric does not` },
    { n: 14, afterSeg: 19, title: `THE TRICK`,                           onScreen: `multiply by r, then subtract` },
    { n: 15, afterSeg: 21, title: `CALL THE TOTAL S`,                    onScreen: `S = 2 + 4 + 8 + 16` },
    { n: 16, afterSeg: 23, title: `MULTIPLY EVERY TERM BY 2`,            onScreen: `2S = 4 + 8 + 16 + 32` },
    { n: 17, afterSeg: 25, title: `SUBTRACT THE LINES`,                  onScreen: `the middle terms cancel` },
    { n: 18, afterSeg: 26, title: `ONLY THE ENDS SURVIVE`,               onScreen: `2S − S = 32 − 2` },
    { n: 19, afterSeg: 27, title: `S = 30`,                              onScreen: `S = 30 ✓ (boxed)` },
    { n: 20, afterSeg: 29, title: `CHECK BY ADDING`,                     onScreen: `2 + 4 + 8 + 16 = 30 ✓` },
    { n: 21, afterSeg: 30, title: `NOW WITH LETTERS`,                    onScreen: `S = a + ar + ar² + … + arⁿ⁻¹` },
    { n: 22, afterSeg: 31, title: `MULTIPLY BY R`,                       onScreen: `rS = ar + ar² + … + arⁿ` },
    { n: 23, afterSeg: 32, title: `SUBTRACT • THE MIDDLE CANCELS`,       onScreen: `rS − S = arⁿ − a` },
    { n: 24, afterSeg: 33, title: `FACTORISE BOTH SIDES`,                onScreen: `S(r − 1) = a(rⁿ − 1)` },
    { n: 25, afterSeg: 34, title: `THE FORMULA`,                         onScreen: `Sₙ = a(rⁿ − 1)/(r − 1) ✓ (boxed)` },
    { n: 26, afterSeg: 35, title: `THE SECOND VERSION`,                  onScreen: `Sₙ = a(1 − rⁿ)/(1 − r)` },
    { n: 27, afterSeg: 36, title: `SAME FORMULA TURNED AROUND`,          onScreen: `r > 1 vs r < 1 — both on the formula sheet` },
    { n: 28, afterSeg: 37, title: `NSC PAPER 1 • NOVEMBER 2014`,         onScreen: `NSC Mathematics P1 · November 2014 · Question 3.2.2` },
    { n: 29, afterSeg: 38, title: `THE QUESTION • SUM OF 10 TERMS`,      onScreen: `3.2.2 Calculate the sum of the first 10 terms. (2)` },
    { n: 30, afterSeg: 41, title: `FIND A AND R`,                        onScreen: `a = 16 · r = 4 ÷ 16 = ¼` },
    { n: 31, afterSeg: 43, title: `CHECK THE RATIO TWICE`,               onScreen: `1 ÷ 4 = ¼ — same ratio ✓` },
    { n: 32, afterSeg: 44, title: `R IS LESS THAN 1`,                    onScreen: `use Sₙ = a(1 − rⁿ)/(1 − r)` },
    { n: 33, afterSeg: 45, title: `SUBSTITUTE`,                          onScreen: `S₁₀ = 16(1 − (¼)¹⁰)/(1 − ¼)` },
    { n: 34, afterSeg: 47, title: `THE BOTTOM`,                          onScreen: `1 − ¼ = ¾` },
    { n: 35, afterSeg: 49, title: `SIXTEEN OVER THREE QUARTERS`,         onScreen: `16 ÷ ¾ = 64/3 = 21,333…` },
    { n: 36, afterSeg: 51, title: `THE TOP • ALMOST NOTHING`,            onScreen: `(¼)¹⁰ ≈ 0,00000095` },
    { n: 37, afterSeg: 54, title: `ANSWER • 21,33`,                      onScreen: `S₁₀ ≈ 21,33 ✓ (boxed)` },
    { n: 38, afterSeg: 55, title: `HOLD THAT THOUGHT`,                   onScreen: `ten terms — and it has barely moved off 21,33` },
    { n: 39, afterSeg: 56, title: `WHERE YOU LOSE MARKS`,                onScreen: `WHERE YOU LOSE MARKS` },
    { n: 40, afterSeg: 57, title: `MARK LOSS 1 • DIVIDE FOR R`,          onScreen: `1. r = later ÷ earlier, never minus` },
    { n: 41, afterSeg: 58, title: `MARK LOSS 2 • N COUNTS TERMS`,        onScreen: `2. n counts terms` },
    { n: 42, afterSeg: 59, title: `MARK LOSS 3 • DO NOT ROUND EARLY`,    onScreen: `3. round only at the end` },
    { n: 43, afterSeg: 60, title: `MARK LOSS 4 • FRACTION RATIO`,        onScreen: `4. r < 1? use the 1 − r version` },
    { n: 44, afterSeg: 61, title: `REMEMBER`,                            onScreen: `REMEMBER` },
    { n: 45, afterSeg: 62, title: `RECAP 1 • ADD OR MULTIPLY`,           onScreen: `1. the series follows the sequence` },
    { n: 46, afterSeg: 63, title: `RECAP 2 • MULTIPLY AND SUBTRACT`,     onScreen: `2. multiply by r, then subtract` },
    { n: 47, afterSeg: 64, title: `RECAP 3 • THE FORMULA`,               onScreen: `3. Sₙ = a(rⁿ − 1)/(r − 1)` },
    { n: 48, afterSeg: 65, title: `YOUR TURN • FIND S20`,                onScreen: `16 + 4 + 1 + … Find S₂₀.` },
    { n: 49, afterSeg: 66, title: `PAUSE AND TRY`,                       onScreen: `PAUSE AND TRY` },
    { n: 50, afterSeg: 69, title: `NEXT • INFINITE GEOMETRIC SERIES`,    onScreen: `NEXT — EPISODE 7: INFINITE GEOMETRIC SERIES` },
  ],
},
