// ─────────────────────────────────────────────────────────────────────────
// EPISODE 7 — paste into the EPISODES array in
// scripts/generate-maths-podcast-audio.mjs, after the episode 6 block
// (immediately before the closing  ];  ).
// Then:  node --env-file=.env.local scripts/generate-maths-podcast-audio.mjs 7
// FIRST: unzip Episode-07-Slides.zip into podcasts/Working-It-Out/slides/ep07
// ─────────────────────────────────────────────────────────────────────────
{
  num: 7,
  file: 'Episode 7 - Infinite Geometric Series',
  segs: [
    { s: 'AMELIA',  t: `Episode seven. Infinite geometric series.` },
    { s: 'MICHAEL', t: `Every episode so far has stopped somewhere. Ten terms. Two hundred and fifty one terms. Today we never stop.` },
    { s: 'NALEDI',  t: `You add numbers forever, and you still get an answer?` },
    { s: 'MICHAEL', t: `Sometimes. And when you can, the formula is the shortest one in the whole topic. But first, your homework.` },
    { s: 'MICHAEL', t: `You had sixteen, plus four, plus one, and so on. I asked you for twenty terms.` },
    { s: 'NALEDI',  t: `Same formula as last time. Sixteen, times, one minus a quarter to the power of twenty, all over three quarters.` },
    { s: 'NALEDI',  t: `And I got twenty one comma three three.` },
    { s: 'MICHAEL', t: `And what did you get for ten terms, last time?` },
    { s: 'NALEDI',  t: `Twenty one comma three three. The same. I added ten more numbers and nothing moved.` },
    { s: 'MICHAEL', t: `Nothing moved. That is today's whole episode.` },
    { s: 'MICHAEL', t: `Look at why. The terms are shrinking. Sixteen, four, one, a quarter, a sixteenth.` },
    { s: 'NALEDI',  t: `By the twentieth term it is almost zero.` },
    { s: 'MICHAEL', t: `So adding it changes almost nothing. The total stops climbing. The exam word is converges.` },
    { s: 'NALEDI',  t: `Converges. Meaning it settles on one number.` },
    { s: 'MICHAEL', t: `It settles. Here is a picture. Stand two metres from a wall. Walk half way. That is one metre.` },
    { s: 'MICHAEL', t: `Then half of what is left. Half a metre. Then half again. A quarter.` },
    { s: 'NALEDI',  t: `I get closer and closer, but I never pass the wall.` },
    { s: 'MICHAEL', t: `And your total distance settles on two metres. One, plus a half, plus a quarter, and so on, adds up to two.` },
    { s: 'MICHAEL', t: `Now the warning. It does not always work. Take two, plus four, plus eight, plus sixteen.` },
    { s: 'NALEDI',  t: `Those are getting bigger, not smaller.` },
    { s: 'MICHAEL', t: `So the total runs away forever. There is no answer. The exam word is diverges.` },
    { s: 'MICHAEL', t: `So there is a condition. The ratio must sit between negative one and one.` },
    { s: 'NALEDI',  t: `Because if the ratio is bigger than one, the terms grow instead of shrinking.` },
    { s: 'MICHAEL', t: `And between negative one and one, every term is a fraction of the one before. Writing that condition down is worth a mark on its own.` },
    { s: 'MICHAEL', t: `Now the formula, and you already have it. Last week you used a, times one minus r to the n, over one minus r.` },
    { s: 'MICHAEL', t: `Think about r to the n when the ratio is a fraction and n gets huge. A quarter to the power of ten was already almost nothing.` },
    { s: 'NALEDI',  t: `So a quarter to the power of a million is basically zero.` },
    { s: 'MICHAEL', t: `So cross it out. The bracket becomes one. And you are left with a, over one minus r.` },
    { s: 'NALEDI',  t: `That is much shorter than I expected.` },
    { s: 'MICHAEL', t: `The sum to infinity is a, over one minus r. Now test it on your homework. First term sixteen, ratio a quarter.` },
    { s: 'NALEDI',  t: `Sixteen over three quarters. That is sixty four over three. Twenty one comma three three three, and it carries on.` },
    { s: 'MICHAEL', t: `And that is the number you have been creeping towards for two episodes. Now you know exactly where it was going.` },
    { s: 'MICHAEL', t: `Now a real exam question. This one is from a different paper. November two thousand and eighteen.` },
    { s: 'MICHAEL', t: `A geometric series has a constant ratio of a half, and a sum to infinity of six. Calculate the first term.` },
    { s: 'NALEDI',  t: `They gave me the answer and they want the beginning. That is backwards.` },
    { s: 'MICHAEL', t: `It is backwards. Write the formula down anyway.` },
    { s: 'NALEDI',  t: `Six equals a, over one minus a half. One minus a half is a half.` },
    { s: 'NALEDI',  t: `So six equals a over a half. Dividing by a half is the same as times two. So a is twelve.` },
    { s: 'MICHAEL', t: `Careful. Check it.` },
    { s: 'NALEDI',  t: `If a is twelve and the ratio is a half, the sum to infinity is twelve over a half. That is twenty four, not six.` },
    { s: 'MICHAEL', t: `So you went the wrong way. Six equals a over a half. To get a on its own, what do you do to both sides?` },
    { s: 'NALEDI',  t: `Multiply both sides by a half. So a is six times a half. Three.` },
    { s: 'MICHAEL', t: `Three. Two marks. Check that one too.` },
    { s: 'NALEDI',  t: `Three over a half is six. Correct.` },
    { s: 'MICHAEL', t: `Next part. Calculate the eighth term.` },
    { s: 'NALEDI',  t: `That is episode two. The enth term is a, times r to the n minus one.` },
    { s: 'NALEDI',  t: `Three, times a half to the power of seven. That is three over one hundred and twenty eight.` },
    { s: 'MICHAEL', t: `Two marks. And notice how small that is already. The eighth term is worth about two hundredths.` },
    { s: 'MICHAEL', t: `Last part, and it uses everything. Sigma, from k equals one to n, of three, times two to the power of, one minus k. The total is five comma eight one two five. Find n.` },
    { s: 'NALEDI',  t: `First, is it really our series? Put k equals one. Two to the power of zero is one. So the first term is three.` },
    { s: 'NALEDI',  t: `Put k equals two. Two to the power of negative one is a half. Three times a half is one comma five.` },
    { s: 'MICHAEL', t: `First term three, ratio a half. The same series.` },
    { s: 'MICHAEL', t: `Now, is this one finite or infinite?` },
    { s: 'NALEDI',  t: `The top is n, not infinity. So it stops. It is finite, and I use last week's formula.` },
    { s: 'NALEDI',  t: `Three, times one minus a half to the power of n, over one minus a half. The bottom is a half, and three divided by a half is six.` },
    { s: 'NALEDI',  t: `So six, times the bracket, equals five comma eight one two five.` },
    { s: 'NALEDI',  t: `Divide both sides by six. The bracket is zero comma nine six eight seven five.` },
    { s: 'NALEDI',  t: `So a half to the power of n is one minus that. One over thirty two.` },
    { s: 'MICHAEL', t: `And a half to the power of what gives one over thirty two?` },
    { s: 'NALEDI',  t: `Two, four, eight, sixteen, thirty two. That is five halvings. So n is five.` },
    { s: 'MICHAEL', t: `n is five. Four marks. And look what you did. You used episode six's formula inside episode seven's question.` },
    { s: 'MICHAEL', t: `Four things.` },
    { s: 'MICHAEL', t: `Number one. Check the ratio before you use the infinity formula. If it is not between negative one and one, there is no answer, and saying so earns the mark.` },
    { s: 'MICHAEL', t: `Number two. The infinity formula has no n in it. If your working still has an n, you are on the wrong formula.` },
    { s: 'MICHAEL', t: `Number three. When they give you the sum and want the first term, do not divide. Multiply the sum by one minus r.` },
    { s: 'MICHAEL', t: `Number four. Sigma with a number on top is finite. Sigma with the infinity sign on top is infinite. Read the top before you choose a formula.` },
    { s: 'MICHAEL', t: `Three things to remember.` },
    { s: 'MICHAEL', t: `One. A series converges when the terms shrink towards zero. That happens when the ratio is between negative one and one.` },
    { s: 'MICHAEL', t: `Two. The sum to infinity is a, over one minus r. Two letters, and no n.` },
    { s: 'MICHAEL', t: `Three. It comes straight from last week's formula, with r to the n crossed out, because it disappears.` },
    { s: 'MICHAEL', t: `And that is the topic. Seven episodes ago you could not find the two hundred and fifty first term. Now you can add up a list that never ends.` },
    { s: 'NALEDI',  t: `And it was really the same few ideas the whole way through.` },
    { s: 'MICHAEL', t: `Find the pattern. Find the rule. Add them up. Check your answer. That is sequences and series. Well done for finishing it.` },
  ],
  slides: [
    { n:  1, afterSeg:  0, title: `EPISODE 7 • INFINITE GEOMETRIC SERIES`, onScreen: `EPISODE 7 — INFINITE GEOMETRIC SERIES` },
    { n:  2, afterSeg:  1, title: `IT ALWAYS STOPPED • TODAY IT DOES NOT`, onScreen: `until now it STOPPED · today it NEVER STOPS` },
    { n:  3, afterSeg:  4, title: `LAST TIME • FIND S20`,                  onScreen: `16 + 4 + 1 + … find S₂₀` },
    { n:  4, afterSeg:  5, title: `SAME FORMULA AS LAST WEEK`,             onScreen: `S₂₀ = 16(1 − (¼)²⁰)/(¾)` },
    { n:  5, afterSeg:  6, title: `ANSWER • 21-33 AGAIN`,                  onScreen: `S₂₀ ≈ 21,33 ✓ (boxed)` },
    { n:  6, afterSeg:  8, title: `TEN TERMS VERSUS TWENTY`,               onScreen: `S₁₀ ≈ 21,33 · S₂₀ ≈ 21,33 — nothing moved` },
    { n:  7, afterSeg: 10, title: `THE TERMS SHRINK`,                      onScreen: `16 → 4 → 1 → ¼ → 1/16` },
    { n:  8, afterSeg: 11, title: `SHRINKING TOWARDS ZERO`,                onScreen: `adding another changes almost nothing` },
    { n:  9, afterSeg: 12, title: `CONVERGES`,                             onScreen: `CONVERGES — the total settles on one number` },
    { n: 10, afterSeg: 15, title: `WALKING TO A WALL`,                     onScreen: `1 m → ½ m → ¼ m …` },
    { n: 11, afterSeg: 17, title: `IT SETTLES ON 2 METRES`,                onScreen: `1 + ½ + ¼ + … = 2 ✓ (boxed)` },
    { n: 12, afterSeg: 18, title: `BUT NOT ALWAYS`,                        onScreen: `2 + 4 + 8 + 16 + …` },
    { n: 13, afterSeg: 20, title: `DIVERGES`,                              onScreen: `DIVERGES — the total runs away, no answer` },
    { n: 14, afterSeg: 21, title: `THE CONDITION`,                         onScreen: `−1 < r < 1 (boxed)` },
    { n: 15, afterSeg: 23, title: `WHY THE CONDITION WORKS`,               onScreen: `r > 1 grows · −1 < r < 1 shrinks` },
    { n: 16, afterSeg: 24, title: `START FROM LAST WEEK`,                  onScreen: `Sₙ = a(1 − rⁿ)/(1 − r)` },
    { n: 17, afterSeg: 26, title: `R TO THE N DISAPPEARS`,                 onScreen: `as n → ∞, rⁿ → 0` },
    { n: 18, afterSeg: 27, title: `SO CROSS IT OUT`,                       onScreen: `the bracket becomes 1` },
    { n: 19, afterSeg: 28, title: `THE SUM TO INFINITY`,                   onScreen: `S∞ = a/(1 − r) ✓ (boxed)` },
    { n: 20, afterSeg: 30, title: `TEST IT ON YOUR OWN SERIES`,            onScreen: `S∞ = 16 ÷ ¾ = 64/3 = 21,333…` },
    { n: 21, afterSeg: 31, title: `THAT IS WHERE IT WAS GOING`,            onScreen: `21,33 was 64/3 all along` },
    { n: 22, afterSeg: 32, title: `NSC PAPER 1 • NOVEMBER 2018`,           onScreen: `NSC Mathematics P1 · November 2018 · Question 3` },
    { n: 23, afterSeg: 33, title: `THE QUESTION 3-1`,                      onScreen: `3.1 r = ½ and S∞ = 6. Calculate the first term. (2)` },
    { n: 24, afterSeg: 36, title: `WRITE THE FORMULA FIRST`,               onScreen: `6 = a ÷ (1 − ½)` },
    { n: 25, afterSeg: 37, title: `NALEDI DIVIDES INSTEAD`,                onScreen: `red · a = 6 × 2 = 12` },
    { n: 26, afterSeg: 39, title: `CHECK IT • IT FAILS`,                   onScreen: `red · 12 ÷ ½ = 24, but S∞ must be 6` },
    { n: 27, afterSeg: 41, title: `MULTIPLY BOTH SIDES INSTEAD`,           onScreen: `a = 6 × ½` },
    { n: 28, afterSeg: 42, title: `ANSWER • A EQUALS 3`,                   onScreen: `a = 3 ✓ (boxed)` },
    { n: 29, afterSeg: 43, title: `CHECK IT`,                              onScreen: `3 ÷ ½ = 6 ✓` },
    { n: 30, afterSeg: 44, title: `THE QUESTION 3-2`,                      onScreen: `3.2 Calculate the 8th term. (2)` },
    { n: 31, afterSeg: 46, title: `T8 EQUALS 3 OVER 128`,                  onScreen: `T₈ = 3(½)⁷ = 3/128 ✓ (boxed)` },
    { n: 32, afterSeg: 47, title: `ALREADY ALMOST NOTHING`,                onScreen: `3/128 ≈ 0,023` },
    { n: 33, afterSeg: 48, title: `THE QUESTION 3-3`,                      onScreen: `3.3 ∑ from k = 1 to n of 3(2)^(1−k) = 5,8125. Find n. (4)` },
    { n: 34, afterSeg: 50, title: `IS IT REALLY OUR SERIES`,               onScreen: `k = 1 → 3 · k = 2 → 1,5` },
    { n: 35, afterSeg: 51, title: `THE SAME SERIES`,                       onScreen: `a = 3 · r = ½ ✓` },
    { n: 36, afterSeg: 53, title: `FINITE OR INFINITE`,                    onScreen: `top is n → finite · top is ∞ → infinite` },
    { n: 37, afterSeg: 54, title: `USE LAST WEEK FORMULA`,                 onScreen: `Sₙ = 6[1 − (½)ⁿ]` },
    { n: 38, afterSeg: 55, title: `SET IT EQUAL TO THE TOTAL`,             onScreen: `6[1 − (½)ⁿ] = 5,8125` },
    { n: 39, afterSeg: 56, title: `DIVIDE BOTH SIDES BY 6`,                onScreen: `1 − (½)ⁿ = 0,96875` },
    { n: 40, afterSeg: 57, title: `MAKE THE POWER THE SUBJECT`,            onScreen: `(½)ⁿ = 1/32` },
    { n: 41, afterSeg: 59, title: `ANSWER • N EQUALS 5`,                   onScreen: `n = 5 ✓ (boxed)` },
    { n: 42, afterSeg: 60, title: `EPISODE 6 INSIDE EPISODE 7`,            onScreen: `it looked infinite — it was finite` },
    { n: 43, afterSeg: 61, title: `WHERE YOU LOSE MARKS`,                  onScreen: `WHERE YOU LOSE MARKS` },
    { n: 44, afterSeg: 62, title: `MARK LOSS 1 • CHECK THE RATIO`,         onScreen: `1. check −1 < r < 1 first` },
    { n: 45, afterSeg: 63, title: `MARK LOSS 2 • NO N`,                    onScreen: `2. no n in the infinity formula` },
    { n: 46, afterSeg: 64, title: `MARK LOSS 3 • MULTIPLY`,                onScreen: `3. a = S∞ × (1 − r)` },
    { n: 47, afterSeg: 65, title: `MARK LOSS 4 • READ THE TOP`,            onScreen: `4. read the top of the sigma` },
    { n: 48, afterSeg: 66, title: `REMEMBER`,                              onScreen: `REMEMBER` },
    { n: 49, afterSeg: 67, title: `RECAP 1 • IT CONVERGES`,                onScreen: `1. terms shrink → it converges` },
    { n: 50, afterSeg: 68, title: `RECAP 2 • THE FORMULA`,                 onScreen: `2. S∞ = a/(1 − r)` },
    { n: 51, afterSeg: 69, title: `RECAP 3 • WHERE IT COMES FROM`,         onScreen: `3. last week's formula with rⁿ gone` },
    { n: 52, afterSeg: 70, title: `SEVEN EPISODES`,                        onScreen: `SEQUENCES & SERIES — seven episodes` },
    { n: 53, afterSeg: 72, title: `THE WHOLE TOPIC`,                       onScreen: `find the pattern · find the rule · add them up · check` },
  ],
},
