// ─────────────────────────────────────────────────────────────────────────
// REVISION PART 1 — EPISODE 1: Algebraic Products   (v2 — every step spoken)
// REPLACES the earlier v1 block. Paste into the EPISODES array in
// scripts/generate-maths-podcast-audio.mjs, replacing the existing
// series: 'Revision-Part-1' object.
// Slides: unzip into podcasts/Working-It-Out/Revision-Part-1/slides/ep01
// Run:    node --env-file=.env.local scripts/generate-maths-podcast-audio.mjs 1
// ─────────────────────────────────────────────────────────────────────────
{
  num: 1,
  series: 'Revision-Part-1',
  file: 'Episode 1 - Algebraic Products',
  segs: [
    { s: 'AMELIA',  t: `Revision, part one. Algebra, exponents and surds. Episode one. Algebraic products.` },
    { s: 'MICHAEL', t: `This is the start of our revision series. These are the skills that Grade twelve assumes you already have.` },
    { s: 'NALEDI',  t: `And if you do not have them?` },
    { s: 'MICHAEL', t: `Then question one of your matric paper is very hard, for no good reason. So we fix that first.` },
    { s: 'MICHAEL', t: `Today, products. A product just means the answer you get when you multiply.` },
    { s: 'NALEDI',  t: `So an algebraic product is what you get when you multiply expressions together.` },
    { s: 'MICHAEL', t: `Yes. And there is one rule for all of them. Every term in the first bracket must multiply every term in the second bracket.` },
    { s: 'NALEDI',  t: `Every term, times every term. Nothing gets left out.` },
    { s: 'MICHAEL', t: `Nothing gets left out. That is the whole topic. Let us do three of them.` },
    { s: 'MICHAEL', t: `First one. Bracket, x plus three, bracket, times, bracket, x minus five.` },
    { s: 'NALEDI',  t: `x times x is x squared.` },
    { s: 'NALEDI',  t: `x times negative five is negative five x.` },
    { s: 'NALEDI',  t: `Three times x is three x.` },
    { s: 'NALEDI',  t: `And three times negative five is negative fifteen.` },
    { s: 'MICHAEL', t: `Watch the signs there. A positive times a negative always gives you a negative.` },
    { s: 'MICHAEL', t: `Now collect the middle two. And you are only allowed to add them because they are both x terms. Same letter, same power.` },
    { s: 'NALEDI',  t: `Negative five x, plus three x. Starting at negative five and going up three gives negative two x.` },
    { s: 'NALEDI',  t: `So x squared, minus two x, minus fifteen.` },
    { s: 'MICHAEL', t: `Two brackets with an x in each gives you a quadratic. An x squared at the front, every time.` },
    { s: 'MICHAEL', t: `Second one, and this is the one people rush. Two x minus one, times, x squared plus three x minus four.` },
    { s: 'NALEDI',  t: `Now the second bracket has three terms.` },
    { s: 'MICHAEL', t: `So there are six multiplications, not four. And there is one rule you need before we start.` },
    { s: 'MICHAEL', t: `When you multiply the same letter, you add the powers. x on its own is really x to the power one. So x times x squared is x to the power three.` },
    { s: 'NALEDI',  t: `One power, plus two powers, gives three powers. That makes sense.` },
    { s: 'MICHAEL', t: `Take the two x first.` },
    { s: 'NALEDI',  t: `Two x times x squared is two x cubed. Two x times three x is six x squared. Two x times negative four is negative eight x.` },
    { s: 'MICHAEL', t: `Now the negative one.` },
    { s: 'NALEDI',  t: `Negative one times x squared is negative x squared. Negative one times three x is negative three x. And negative one times negative four is positive four.` },
    { s: 'MICHAEL', t: `Two negatives make a positive. That sign is worth checking every single time.` },
    { s: 'MICHAEL', t: `Now collect the like terms. Only the x squareds go together, and only the x terms go together.` },
    { s: 'NALEDI',  t: `Six x squared minus x squared is five x squared. Negative eight x minus three x is negative eleven x.` },
    { s: 'NALEDI',  t: `So two x cubed, plus five x squared, minus eleven x, plus four.` },
    { s: 'MICHAEL', t: `A linear bracket times a quadratic bracket gives a cubic. An x cubed at the front.` },
    { s: 'MICHAEL', t: `Third one. And this is where marks disappear. Bracket, x minus four, bracket, squared.` },
    { s: 'NALEDI',  t: `Squared. So, x squared minus sixteen.` },
    { s: 'MICHAEL', t: `Test it. Put x equals one into your answer.` },
    { s: 'NALEDI',  t: `One, minus sixteen. Negative fifteen.` },
    { s: 'MICHAEL', t: `Now put x equals one into the original. One minus four, and then squared.` },
    { s: 'NALEDI',  t: `Negative three, squared. That is positive nine.` },
    { s: 'NALEDI',  t: `Nine is not negative fifteen. So I am wrong.` },
    { s: 'MICHAEL', t: `You are. Squaring a bracket does not square the terms separately. Write it out as two brackets and use the rule.` },
    { s: 'NALEDI',  t: `x minus four, times, x minus four.` },
    { s: 'NALEDI',  t: `x squared, minus four x, minus four x, plus sixteen.` },
    { s: 'NALEDI',  t: `So x squared, minus eight x, plus sixteen.` },
    { s: 'MICHAEL', t: `And test it again. x equals one gives one, minus eight, plus sixteen.` },
    { s: 'NALEDI',  t: `Nine. It matches now.` },
    { s: 'MICHAEL', t: `There are three of these worth knowing by sight. They come up constantly.` },
    { s: 'MICHAEL', t: `a plus b, squared, is a squared, plus two a b, plus b squared.` },
    { s: 'NALEDI',  t: `Where does the two a b come from?` },
    { s: 'MICHAEL', t: `Write it as two brackets and you will see. a times b gives you a b. And b times a gives you a b again. Two lots of a b.` },
    { s: 'MICHAEL', t: `a minus b, squared, is a squared, minus two a b, plus b squared.` },
    { s: 'MICHAEL', t: `And a plus b, times a minus b, is a squared minus b squared. There you get plus a b and minus a b, so the middle cancels.` },
    { s: 'NALEDI',  t: `So only the last one loses its middle term.` },
    { s: 'MICHAEL', t: `Only that one. The other two keep it, and forgetting it is the mistake you just made.` },
    { s: 'MICHAEL', t: `Now, does this actually appear in matric? Here is November two thousand and sixteen, question one point three.` },
    { s: 'MICHAEL', t: `Solve for x and y, if x equals two y, and x squared minus five x y equals negative twenty four.` },
    { s: 'NALEDI',  t: `That looks like simultaneous equations, not products.` },
    { s: 'MICHAEL', t: `It is. But look what happens when you substitute. Replace every x with two y.` },
    { s: 'NALEDI',  t: `Bracket two y bracket, squared, minus five, times two y, times y.` },
    { s: 'MICHAEL', t: `And now you are expanding. Careful with that first part.` },
    { s: 'NALEDI',  t: `Two y, squared, means two y times two y. Two times two is four, and y times y is y squared. So it is four y squared.` },
    { s: 'MICHAEL', t: `And the second part?` },
    { s: 'NALEDI',  t: `Five times two is ten. And y times y is y squared. So that is ten y squared.` },
    { s: 'NALEDI',  t: `So four y squared minus ten y squared is negative six y squared, and that equals negative twenty four.` },
    { s: 'MICHAEL', t: `Divide both sides by negative six.` },
    { s: 'NALEDI',  t: `y squared equals four. So y is two.` },
    { s: 'MICHAEL', t: `Careful. What else, squared, gives you four?` },
    { s: 'NALEDI',  t: `Negative two. Negative two, squared, is also four. So y is two, or negative two.` },
    { s: 'MICHAEL', t: `Both of them. Miss the negative one and you lose a mark. And x is two y, so x is four, or negative four.` },
    { s: 'MICHAEL', t: `That is a four mark question, and the only hard part was expanding correctly.` },
    { s: 'MICHAEL', t: `Three things.` },
    { s: 'MICHAEL', t: `Number one. Every term times every term. Two terms times three terms is six multiplications.` },
    { s: 'MICHAEL', t: `Number two. Squaring a bracket is not squaring the terms. Write it out as two brackets first.` },
    { s: 'MICHAEL', t: `Number three. When you square something like two y, the number gets squared too. Two y, squared, is four y squared.` },
    { s: 'MICHAEL', t: `Two things to remember.` },
    { s: 'MICHAEL', t: `One. A linear bracket times a linear bracket gives a quadratic. Times a quadratic bracket gives a cubic.` },
    { s: 'MICHAEL', t: `Two. If you are not sure, test your answer with a number. Put x equals one into both, and see if they match.` },
    { s: 'MICHAEL', t: `Here is your question. Expand, x plus five, times, x minus two.` },
    { s: 'MICHAEL', t: `Pause and try it. I will wait.`, pause: 3.0 },
    { s: 'MICHAEL', t: `I will give you the answer next time. And next time we do the same thing backwards.` },
    { s: 'NALEDI',  t: `Backwards?` },
    { s: 'MICHAEL', t: `Today we multiplied brackets out. Next time we take an expression and put the brackets back. That is factorising, and it is episode two.` },
  ],
  slides: [
    { n:  1, afterSeg:  0, title: `REVISION 1 • EPISODE 1 • ALGEBRAIC PRODUCTS`, onScreen: `EPISODE 1 — ALGEBRAIC PRODUCTS` },
    { n:  2, afterSeg:  1, title: `WHAT REVISION PART 1 IS`,          onScreen: `the skills Grade 12 assumes you have` },
    { n:  3, afterSeg:  3, title: `QUESTION 1 GETS EASIER`,           onScreen: `~25 marks of Paper 1 live here` },
    { n:  4, afterSeg:  4, title: `A PRODUCT`,                        onScreen: `the answer you get when you multiply` },
    { n:  5, afterSeg:  6, title: `THE ONE RULE`,                     onScreen: `every term × every term` },
    { n:  6, afterSeg:  8, title: `EXAMPLE 1`,                        onScreen: `(x + 3)(x − 5)` },
    { n:  7, afterSeg: 10, title: `START WITH THE X`,                 onScreen: `x × x = x² · x × (−5) = −5x` },
    { n:  8, afterSeg: 13, title: `NOW THE 3`,                        onScreen: `3 × x = 3x · 3 × (−5) = −15` },
    { n:  9, afterSeg: 14, title: `THE SIGN RULES`,                   onScreen: `+ × − → negative · − × − → positive` },
    { n: 10, afterSeg: 15, title: `LIKE TERMS`,                       onScreen: `same letter, same power` },
    { n: 11, afterSeg: 16, title: `COLLECT THE MIDDLE TWO`,           onScreen: `−5x + 3x = −2x` },
    { n: 12, afterSeg: 17, title: `ANSWER 1`,                         onScreen: `x² − 2x − 15 ✓ (boxed)` },
    { n: 13, afterSeg: 18, title: `LINEAR TIMES LINEAR`,              onScreen: `→ a quadratic` },
    { n: 14, afterSeg: 19, title: `EXAMPLE 2`,                        onScreen: `(2x − 1)(x² + 3x − 4)` },
    { n: 15, afterSeg: 21, title: `SIX MULTIPLICATIONS`,              onScreen: `2 terms × 3 terms = six, not four` },
    { n: 16, afterSeg: 22, title: `ADD THE POWERS`,                   onScreen: `x is really x¹` },
    { n: 17, afterSeg: 23, title: `WHY X TIMES X SQUARED IS X CUBED`, onScreen: `1 + 2 = 3` },
    { n: 18, afterSeg: 25, title: `TAKE THE 2X FIRST`,                onScreen: `2x³ · 6x² · −8x` },
    { n: 19, afterSeg: 27, title: `NOW THE MINUS 1`,                  onScreen: `−x² · −3x · +4` },
    { n: 20, afterSeg: 28, title: `TWO NEGATIVES MAKE A POSITIVE`,    onScreen: `−1 × −4 = +4` },
    { n: 21, afterSeg: 29, title: `COLLECT LIKE TERMS`,               onScreen: `5x² · −11x` },
    { n: 22, afterSeg: 31, title: `ANSWER 2`,                         onScreen: `2x³ + 5x² − 11x + 4 ✓ (boxed)` },
    { n: 23, afterSeg: 32, title: `LINEAR TIMES QUADRATIC`,           onScreen: `→ a cubic` },
    { n: 24, afterSeg: 33, title: `EXAMPLE 3`,                        onScreen: `(x − 4)²` },
    { n: 25, afterSeg: 34, title: `NALEDI SQUARES EACH TERM`,         onScreen: `red · x² − 16` },
    { n: 26, afterSeg: 36, title: `TEST IT • PUT X EQUALS 1`,         onScreen: `red · = −15` },
    { n: 27, afterSeg: 38, title: `THE ORIGINAL AT X EQUALS 1`,       onScreen: `(−3)² = 9` },
    { n: 28, afterSeg: 39, title: `IT DOES NOT MATCH`,                onScreen: `red · 9 ≠ −15 ✗` },
    { n: 29, afterSeg: 41, title: `WRITE IT AS TWO BRACKETS`,         onScreen: `(x − 4)(x − 4)` },
    { n: 30, afterSeg: 42, title: `EVERY TERM TIMES EVERY TERM`,      onScreen: `x² − 4x − 4x + 16` },
    { n: 31, afterSeg: 43, title: `ANSWER 3`,                         onScreen: `x² − 8x + 16 ✓ (boxed)` },
    { n: 32, afterSeg: 45, title: `TEST IT AGAIN`,                    onScreen: `= 9 ✓ it matches` },
    { n: 33, afterSeg: 47, title: `SPECIAL PRODUCT 1`,                onScreen: `(a + b)² = a² + 2ab + b²` },
    { n: 34, afterSeg: 49, title: `WHERE THE 2AB COMES FROM`,         onScreen: `ab from each side → 2ab` },
    { n: 35, afterSeg: 50, title: `SPECIAL PRODUCT 2`,                onScreen: `(a − b)² = a² − 2ab + b²` },
    { n: 36, afterSeg: 51, title: `SPECIAL PRODUCT 3`,                onScreen: `+ab and −ab cancel → a² − b²` },
    { n: 37, afterSeg: 53, title: `ONLY THE THIRD LOSES ITS MIDDLE`,  onScreen: `the two squares keep it` },
    { n: 38, afterSeg: 54, title: `NSC PAPER 1 • NOVEMBER 2016`,      onScreen: `NSC Mathematics P1 · Nov 2016 · Q1.3` },
    { n: 39, afterSeg: 55, title: `THE QUESTION 1-3`,                 onScreen: `x = 2y and x² − 5xy = −24. (4)` },
    { n: 40, afterSeg: 58, title: `SUBSTITUTE`,                       onScreen: `(2y)² − 5(2y)(y) = −24` },
    { n: 41, afterSeg: 60, title: `THE 2 GETS SQUARED TOO`,           onScreen: `(2y)² = 4y²` },
    { n: 42, afterSeg: 62, title: `NOW THE SECOND PART`,              onScreen: `5(2y)(y) = 10y²` },
    { n: 43, afterSeg: 63, title: `PUT IT TOGETHER`,                  onScreen: `−6y² = −24` },
    { n: 44, afterSeg: 64, title: `DIVIDE BOTH SIDES BY MINUS 6`,     onScreen: `y² = 4` },
    { n: 45, afterSeg: 66, title: `WHAT ELSE SQUARED GIVES 4`,        onScreen: `(−2)² = 4 as well` },
    { n: 46, afterSeg: 67, title: `BOTH VALUES OF Y`,                 onScreen: `y = 2 or y = −2 ✓ (boxed)` },
    { n: 47, afterSeg: 68, title: `ANSWER • BOTH PAIRS`,              onScreen: `(4 ; 2) or (−4 ; −2) ✓ (boxed)` },
    { n: 48, afterSeg: 69, title: `FOUR MARKS`,                       onScreen: `the only hard part was expanding` },
    { n: 49, afterSeg: 70, title: `WHERE YOU LOSE MARKS`,             onScreen: `WHERE YOU LOSE MARKS` },
    { n: 50, afterSeg: 71, title: `MARK LOSS 1 • EVERY TERM`,         onScreen: `1. six multiplications, not four` },
    { n: 51, afterSeg: 72, title: `MARK LOSS 2 • SQUARING A BRACKET`, onScreen: `2. write it out as two brackets` },
    { n: 52, afterSeg: 73, title: `MARK LOSS 3 • SQUARE THE NUMBER`,  onScreen: `3. (2y)² = 4y², never 2y²` },
    { n: 53, afterSeg: 74, title: `REMEMBER`,                         onScreen: `REMEMBER` },
    { n: 54, afterSeg: 75, title: `RECAP 1 • THE ANSWER SHAPE`,       onScreen: `1. linear × linear → quadratic` },
    { n: 55, afterSeg: 76, title: `RECAP 2 • TEST WITH A NUMBER`,     onScreen: `2. put x = 1 into both` },
    { n: 56, afterSeg: 77, title: `YOUR TURN`,                        onScreen: `Expand (x + 5)(x − 2)` },
    { n: 57, afterSeg: 78, title: `PAUSE AND TRY`,                    onScreen: `PAUSE AND TRY` },
    { n: 58, afterSeg: 81, title: `NEXT • FACTORISING`,               onScreen: `NEXT — EPISODE 2: FACTORISING` },
  ],
},
