// ─────────────────────────────────────────────────────────────────────────
// REVISION PART 1 — EPISODE 1: Algebraic Products
// Paste into the EPISODES array in scripts/generate-maths-podcast-audio.mjs
// (immediately before the closing  ];  ).
// FIRST: unzip Revision-1-Episode-01-Slides.zip into
//        podcasts/Working-It-Out/Revision-Part-1/slides/ep01
// Then:  node --env-file=.env.local scripts/generate-maths-podcast-audio.mjs 1
//        (the `series` field keeps it away from Sequences episode 1)
// ─────────────────────────────────────────────────────────────────────────
{
  num: 1,
  series: 'Revision-Part-1',
  file: 'Episode 1 - Algebraic Products',
  segs: [
    { s: 'AMELIA',  t: `Revision, part one. Algebra, exponents and surds. Episode one. Algebraic products.` },
    { s: 'MICHAEL', t: `This is the start of our revision series. These are the skills that Grade twelve assumes you already have.` },
    { s: 'NALEDI',  t: `And if you do not have them?` },
    { s: 'MICHAEL', t: `Then question one of your matric paper is very hard, for no good reason. So we fix that first.` },
    { s: 'MICHAEL', t: `Today, products. A product just means the answer you get when you multiply.` },
    { s: 'NALEDI',  t: `So an algebraic product is what you get when you multiply expressions together.` },
    { s: 'MICHAEL', t: `Yes. And there is one rule for all of them. Every term in the first bracket must multiply every term in the second bracket.` },
    { s: 'NALEDI',  t: `Every term, times every term. Nothing gets left out.` },
    { s: 'MICHAEL', t: `Nothing gets left out. That is the whole topic. Let us do three of them.` },
    { s: 'MICHAEL', t: `First one. Bracket, x plus three, bracket, times, bracket, x minus five.` },
    { s: 'NALEDI',  t: `x times x is x squared.` },
    { s: 'NALEDI',  t: `x times negative five is negative five x.` },
    { s: 'NALEDI',  t: `Three times x is three x.` },
    { s: 'NALEDI',  t: `And three times negative five is negative fifteen.` },
    { s: 'MICHAEL', t: `Now collect the middle two.` },
    { s: 'NALEDI',  t: `Negative five x, plus three x, is negative two x.` },
    { s: 'NALEDI',  t: `So x squared, minus two x, minus fifteen.` },
    { s: 'MICHAEL', t: `Two brackets with an x in each gives you a quadratic. An x squared at the front, every time.` },
    { s: 'MICHAEL', t: `Second one, and this is the one people rush. Two x minus one, times, x squared plus three x minus four.` },
    { s: 'NALEDI',  t: `Now the second bracket has three terms.` },
    { s: 'MICHAEL', t: `So there are six multiplications, not four. Take the two x first.` },
    { s: 'NALEDI',  t: `Two x times x squared is two x cubed. Two x times three x is six x squared. Two x times negative four is negative eight x.` },
    { s: 'MICHAEL', t: `Now the negative one.` },
    { s: 'NALEDI',  t: `Negative one times x squared is negative x squared. Negative one times three x is negative three x. And negative one times negative four is positive four.` },
    { s: 'MICHAEL', t: `Collect the like terms.` },
    { s: 'NALEDI',  t: `Six x squared minus x squared is five x squared. Negative eight x minus three x is negative eleven x.` },
    { s: 'NALEDI',  t: `So two x cubed, plus five x squared, minus eleven x, plus four.` },
    { s: 'MICHAEL', t: `A linear bracket times a quadratic bracket gives a cubic. An x cubed at the front.` },
    { s: 'MICHAEL', t: `Third one. And this is where marks disappear. Bracket, x minus four, bracket, squared.` },
    { s: 'NALEDI',  t: `Squared. So, x squared minus sixteen.` },
    { s: 'MICHAEL', t: `Test it. Put x equals one into your answer.` },
    { s: 'NALEDI',  t: `One, minus sixteen. Negative fifteen.` },
    { s: 'MICHAEL', t: `Now put x equals one into the original. One minus four, and then squared.` },
    { s: 'NALEDI',  t: `Negative three, squared. That is positive nine.` },
    { s: 'NALEDI',  t: `Nine is not negative fifteen. So I am wrong.` },
    { s: 'MICHAEL', t: `You are. Squaring a bracket does not square the terms separately. Write it out as two brackets and use the rule.` },
    { s: 'NALEDI',  t: `x minus four, times, x minus four.` },
    { s: 'NALEDI',  t: `x squared, minus four x, minus four x, plus sixteen.` },
    { s: 'NALEDI',  t: `So x squared, minus eight x, plus sixteen.` },
    { s: 'MICHAEL', t: `And test it again. x equals one gives one, minus eight, plus sixteen.` },
    { s: 'NALEDI',  t: `Nine. It matches now.` },
    { s: 'MICHAEL', t: `There are three of these worth knowing by sight. They come up constantly.` },
    { s: 'MICHAEL', t: `a plus b, squared, is a squared, plus two a b, plus b squared.` },
    { s: 'MICHAEL', t: `a minus b, squared, is a squared, minus two a b, plus b squared.` },
    { s: 'MICHAEL', t: `And a plus b, times a minus b, is a squared minus b squared. The middle terms cancel in that one.` },
    { s: 'NALEDI',  t: `So only the last one loses its middle term.` },
    { s: 'MICHAEL', t: `Only that one. The other two keep it, and forgetting it is the mistake you just made.` },
    { s: 'MICHAEL', t: `Now, does this actually appear in matric? Here is November two thousand and sixteen, question one point three.` },
    { s: 'MICHAEL', t: `Solve for x and y, if x equals two y, and x squared minus five x y equals negative twenty four.` },
    { s: 'NALEDI',  t: `That looks like simultaneous equations, not products.` },
    { s: 'MICHAEL', t: `It is. But look what happens when you substitute. Replace every x with two y.` },
    { s: 'NALEDI',  t: `Bracket two y bracket, squared, minus five, times two y, times y.` },
    { s: 'MICHAEL', t: `And now you are expanding. Careful with that first part.` },
    { s: 'NALEDI',  t: `Two y, squared, is four y squared. Because the two gets squared as well.` },
    { s: 'MICHAEL', t: `And the second part?` },
    { s: 'NALEDI',  t: `Five, times two y, times y, is ten y squared.` },
    { s: 'NALEDI',  t: `So four y squared minus ten y squared is negative six y squared, and that equals negative twenty four.` },
    { s: 'MICHAEL', t: `Which gives y squared equals four. So y is two, or negative two. And x is two y, so four, or negative four.` },
    { s: 'MICHAEL', t: `That is a four mark question, and the only hard part was expanding correctly.` },
    { s: 'MICHAEL', t: `Three things.` },
    { s: 'MICHAEL', t: `Number one. Every term times every term. Two terms times three terms is six multiplications.` },
    { s: 'MICHAEL', t: `Number two. Squaring a bracket is not squaring the terms. Write it out as two brackets first.` },
    { s: 'MICHAEL', t: `Number three. When you square something like two y, the number gets squared too. Two y, squared, is four y squared.` },
    { s: 'MICHAEL', t: `Two things to remember.` },
    { s: 'MICHAEL', t: `One. A linear bracket times a linear bracket gives a quadratic. Times a quadratic bracket gives a cubic.` },
    { s: 'MICHAEL', t: `Two. If you are not sure, test your answer with a number. Put x equals one into both, and see if they match.` },
    { s: 'MICHAEL', t: `Here is your question. Expand, x plus five, times, x minus two.` },
    { s: 'MICHAEL', t: `Pause and try it. I will wait.`, pause: 3.0 },
    { s: 'MICHAEL', t: `I will give you the answer next time. And next time we do the same thing backwards.` },
    { s: 'NALEDI',  t: `Backwards?` },
    { s: 'MICHAEL', t: `Today we multiplied brackets out. Next time we take an expression and put the brackets back. That is factorising, and it is episode two.` },
  ],
  slides: [
    { n:  1, afterSeg:  0, title: `REVISION 1 • EPISODE 1 • ALGEBRAIC PRODUCTS`, onScreen: `EPISODE 1 — ALGEBRAIC PRODUCTS` },
    { n:  2, afterSeg:  1, title: `WHAT REVISION PART 1 IS`,            onScreen: `the skills Grade 12 assumes you have` },
    { n:  3, afterSeg:  3, title: `QUESTION 1 GETS EASIER`,             onScreen: `~25 marks of Paper 1 live here` },
    { n:  4, afterSeg:  4, title: `A PRODUCT`,                          onScreen: `the answer you get when you multiply` },
    { n:  5, afterSeg:  6, title: `THE ONE RULE`,                       onScreen: `every term × every term` },
    { n:  6, afterSeg:  8, title: `EXAMPLE 1`,                          onScreen: `(x + 3)(x − 5)` },
    { n:  7, afterSeg: 10, title: `START WITH THE X`,                   onScreen: `x × x = x² · x × (−5) = −5x` },
    { n:  8, afterSeg: 13, title: `NOW THE 3`,                          onScreen: `3 × x = 3x · 3 × (−5) = −15` },
    { n:  9, afterSeg: 15, title: `COLLECT THE MIDDLE TWO`,             onScreen: `−5x + 3x = −2x` },
    { n: 10, afterSeg: 16, title: `ANSWER 1`,                           onScreen: `x² − 2x − 15 ✓ (boxed)` },
    { n: 11, afterSeg: 17, title: `LINEAR TIMES LINEAR`,                onScreen: `→ a quadratic` },
    { n: 12, afterSeg: 18, title: `EXAMPLE 2`,                          onScreen: `(2x − 1)(x² + 3x − 4)` },
    { n: 13, afterSeg: 20, title: `SIX MULTIPLICATIONS`,                onScreen: `2 terms × 3 terms = six, not four` },
    { n: 14, afterSeg: 21, title: `TAKE THE 2X FIRST`,                  onScreen: `2x³ · 6x² · −8x` },
    { n: 15, afterSeg: 23, title: `NOW THE MINUS 1`,                    onScreen: `−x² · −3x · +4` },
    { n: 16, afterSeg: 25, title: `COLLECT LIKE TERMS`,                 onScreen: `5x² · −11x` },
    { n: 17, afterSeg: 26, title: `ANSWER 2`,                           onScreen: `2x³ + 5x² − 11x + 4 ✓ (boxed)` },
    { n: 18, afterSeg: 27, title: `LINEAR TIMES QUADRATIC`,             onScreen: `→ a cubic` },
    { n: 19, afterSeg: 28, title: `EXAMPLE 3`,                          onScreen: `(x − 4)²` },
    { n: 20, afterSeg: 29, title: `NALEDI SQUARES EACH TERM`,           onScreen: `red · x² − 16` },
    { n: 21, afterSeg: 31, title: `TEST IT • PUT X EQUALS 1`,           onScreen: `red · = −15` },
    { n: 22, afterSeg: 33, title: `THE ORIGINAL AT X EQUALS 1`,         onScreen: `(−3)² = 9` },
    { n: 23, afterSeg: 34, title: `IT DOES NOT MATCH`,                  onScreen: `red · 9 ≠ −15 ✗` },
    { n: 24, afterSeg: 36, title: `WRITE IT AS TWO BRACKETS`,           onScreen: `(x − 4)(x − 4)` },
    { n: 25, afterSeg: 37, title: `EVERY TERM TIMES EVERY TERM`,        onScreen: `x² − 4x − 4x + 16` },
    { n: 26, afterSeg: 38, title: `ANSWER 3`,                           onScreen: `x² − 8x + 16 ✓ (boxed)` },
    { n: 27, afterSeg: 40, title: `TEST IT AGAIN`,                      onScreen: `= 9 ✓ it matches` },
    { n: 28, afterSeg: 42, title: `SPECIAL PRODUCT 1`,                  onScreen: `(a + b)² = a² + 2ab + b²` },
    { n: 29, afterSeg: 43, title: `SPECIAL PRODUCT 2`,                  onScreen: `(a − b)² = a² − 2ab + b²` },
    { n: 30, afterSeg: 44, title: `SPECIAL PRODUCT 3`,                  onScreen: `(a + b)(a − b) = a² − b²` },
    { n: 31, afterSeg: 46, title: `ONLY THE THIRD LOSES ITS MIDDLE`,    onScreen: `the two squares keep it` },
    { n: 32, afterSeg: 47, title: `NSC PAPER 1 • NOVEMBER 2016`,        onScreen: `NSC Mathematics P1 · Nov 2016 · Q1.3` },
    { n: 33, afterSeg: 48, title: `THE QUESTION 1-3`,                   onScreen: `x = 2y and x² − 5xy = −24. Solve for x and y. (4)` },
    { n: 34, afterSeg: 51, title: `SUBSTITUTE`,                         onScreen: `(2y)² − 5(2y)(y) = −24` },
    { n: 35, afterSeg: 53, title: `THE 2 GETS SQUARED TOO`,             onScreen: `(2y)² = 4y²` },
    { n: 36, afterSeg: 55, title: `NOW THE SECOND PART`,                onScreen: `5(2y)(y) = 10y²` },
    { n: 37, afterSeg: 56, title: `PUT IT TOGETHER`,                    onScreen: `−6y² = −24 → y² = 4` },
    { n: 38, afterSeg: 57, title: `ANSWER • BOTH PAIRS`,                onScreen: `(4 ; 2) or (−4 ; −2) ✓ (boxed)` },
    { n: 39, afterSeg: 58, title: `FOUR MARKS`,                         onScreen: `the only hard part was expanding` },
    { n: 40, afterSeg: 59, title: `WHERE YOU LOSE MARKS`,               onScreen: `WHERE YOU LOSE MARKS` },
    { n: 41, afterSeg: 60, title: `MARK LOSS 1 • EVERY TERM`,           onScreen: `1. six multiplications, not four` },
    { n: 42, afterSeg: 61, title: `MARK LOSS 2 • SQUARING A BRACKET`,   onScreen: `2. write it out as two brackets` },
    { n: 43, afterSeg: 62, title: `MARK LOSS 3 • SQUARE THE NUMBER`,    onScreen: `3. (2y)² = 4y², never 2y²` },
    { n: 44, afterSeg: 63, title: `REMEMBER`,                           onScreen: `REMEMBER` },
    { n: 45, afterSeg: 64, title: `RECAP 1 • THE ANSWER SHAPE`,         onScreen: `1. linear × linear → quadratic` },
    { n: 46, afterSeg: 65, title: `RECAP 2 • TEST WITH A NUMBER`,       onScreen: `2. put x = 1 into both` },
    { n: 47, afterSeg: 66, title: `YOUR TURN`,                          onScreen: `Expand (x + 5)(x − 2)` },
    { n: 48, afterSeg: 67, title: `PAUSE AND TRY`,                      onScreen: `PAUSE AND TRY` },
    { n: 49, afterSeg: 70, title: `NEXT • FACTORISING`,                 onScreen: `NEXT — EPISODE 2: FACTORISING` },
  ],
},
